name: yeash
description: oh yeah

dependencies:
  screen:
  flutter:
    sdk: flutter
  flame:
  flutter_midi:
    path: C:\Users\idiscipulo\Programming\flutter_midi
  dart_midi:
        
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_midi:
    path: C:\Users\whois\dev\flutter\flutter_midi
  # flutter_midi:
  #   path: C:\Users\idiscipulo\Programming\flutter_midi

flutter:
  # add assets here
  assets:
    - assets/songs/test_song/midi/test_song.MID
    - assets/songs/test_song/sound/test-song.wav
